#
# JulLocationBundle Symfony package.
#
# © 2013 Julien Tord <http://github.com/youlweb/JulLocationBundle>
#
# Full license information in the LICENSE text file distributed
# with this source code.
#

Jul\LocationBundle\Entity\Location:

    type: mappedSuperclass
    
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    
    fields:
    
        name:
            type: string
            length: 128
            nullable: true

        long_name:
            type: string
            nullable: true
        
        slug:
            type: string
            nullable: true
        
        address:
            type: text
            nullable: true
        
        long_address:
            type: text
            nullable: true
        
        postcode:
            type: string
            length: 10
            nullable: true
        
        latitude:
            type: float
            nullable: true
        
        longitude:
            type: float
            nullable: true
        
        image_url:
            type: text
            nullable: true
        
        website_url:
            type: text
            nullable: true
        
        phone:
            type: string
            nullable: true
        
