#
# JulLocationBundle Symfony package.
#
# © 2013 Julien Tord <http://github.com/youlweb/JulLocationBundle>
#
# Full license information in the LICENSE text file distributed
# with this source code.
#

services:
    
    form.type.JulLocationField:
        class: Jul\LocationBundle\Form\Type\LocationType
        arguments: [ "location", "@doctrine.orm.entity_manager", "%jul_location.options%" ]
        tags:
            - { name: form.type, alias: JulLocationField }
    
    form.type.JulCityField:
        class: Jul\LocationBundle\Form\Type\LocationType
        arguments: [ "city", "@doctrine.orm.entity_manager", "%jul_location.options%" ]
        tags:
            - { name: form.type, alias: JulCityField }
    
    form.type.JulStateField:
        class: Jul\LocationBundle\Form\Type\LocationType
        arguments: [ "state", "@doctrine.orm.entity_manager", "%jul_location.options%" ]
        tags:
            - { name: form.type, alias: JulStateField }
                
    form.type.JulCountryField:
        class: Jul\LocationBundle\Form\Type\LocationType
        arguments: [ "country", "@doctrine.orm.entity_manager", "%jul_location.options%" ]
        tags:
            - { name: form.type, alias: JulCountryField }
    
    