services:

    form.type.cityField:
            class: Jul\LocationBundle\Form\Type\CityType
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: form.type, alias: cityField }